### ISSUE TITLE
训练运行train.py 运行到 vae = AutoencoderKL.from_pretrained(opt.stable_dif_path, subfolder="vae")报错

### ISSUE THREAD

**Issue by alchemist-zsh** [dailenson/One-DM#22]
你好，训练运行train.py 运行到 vae = AutoencoderKL.from_pretrained(opt.stable_dif_path, subfolder="vae")报错（如下），没有找到diffusion_pytorch_model.bin，请问能否把需要的runwayml/stable-diffusion-v1-5里面的模型也上传一下，因为huggingface 里面的runwayml/stable-diffusion-v1-5已经删掉了，在其他地方下载的不正确报了这个错误。

Exception has occurred: OSError
Error no file named diffusion_pytorch_model.bin found in directory /media/hzs/data/hzs/One-DM-main/runwayml/stable-diffusion-v1-5.
  File "/media/One-DM-main/train.py", line 92, in main
    vae = AutoencoderKL.from_pretrained(opt.stable_dif_path, subfolder="vae")
  File "/media/One-DM-main/train.py", line 115, in <module>
    main(opt)
OSError: Error no file named diffusion_pytorch_model.bin found in directory /media/hzs/data/hzs/One-DM-main/runwayml/stable-diffusion-v1-5.

**Comment by dailenson** [comment]
你好~感谢提醒。stable-diffusion-v1-5已经上传：https://wisemodel.cn/models/SCUT-MMPR/One-DM/file

**Comment by alchemist-zsh** [comment]
可以训练了，谢谢
