### ISSUE TITLE
classifier-free guidance strategy

### ISSUE THREAD

**Issue by xjia666** [dailenson/One-DM#30]
您好，我看您论文中说使用了classifier-free guidance strategy，但是我在代码中没有找到这部分代码，您可以指出这部分代码的位置吗

**Comment by dailenson** [comment]
你好，这部分代码在整理的时候被我删掉了，个人感觉对性能帮助不算大。可以在这个地方加上，控制condition drop的频率。https://github.com/dailenson/One-DM/blob/ca01eb13e7766eea3e349b2f369ea6f18707e5a5/trainer/trainer.py#L52
